export type ThemeMode = "light" | "dark";
export type ThemeTypeface = "sans" | "serif" | "mono";

export type AiTarget = "chatgpt" | "claude" | "v0" | "cursor";

export type ThemeTokens = {
  bg: string;
  surface: string;
  border: string;
  text: string;
  textMuted: string;
  primary: string;
  primaryText: string;
  secondary: string;
  secondaryText: string;
  accent: string;
  fontHeading: string;
  fontBody: string;
  letterSpacingHeading: string;
  radius: string;
  borderWidth: string;
  shadow: string;
  weightHeading: number;
  headingCase: "normal" | "uppercase";
  grain?: boolean;
  decoration?: "none" | "scanlines" | "grid" | "shapes";
};

export type ThemeSample = {
  brand: string;
  eyebrow: string;
  headline: string;
  subcopy: string;
  primaryCta: string;
  secondaryCta: string;
  navLinks: [string, string, string];
};

export type ThemeEntry = {
  id: string;
  name: string;
  description: string;
  mode: ThemeMode;
  typeface: ThemeTypeface;
  tags: string[];
  swatch: string[];
  tokens: ThemeTokens;
  sample: ThemeSample;
  prompts: Record<AiTarget, string>;
};

const SANS =
  '"Inter","Geist","Helvetica Neue",ui-sans-serif,system-ui,sans-serif';
const SERIF =
  '"Source Serif Pro","Playfair Display","Times New Roman",Georgia,serif';
const MONO =
  '"JetBrains Mono","IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,monospace';
const DISPLAY_SERIF =
  '"Playfair Display","Libre Bodoni",Georgia,serif';

const DEFAULT_SAMPLE: ThemeSample = {
  brand: "Acme Inc.",
  eyebrow: "NOW AVAILABLE",
  headline: "Transform the way your team works",
  subcopy:
    "Acme Platform brings your team together with powerful tools designed to streamline workflows, boost productivity, and drive results.",
  primaryCta: "Start free trial",
  secondaryCta: "Watch demo",
  navLinks: ["Features", "Pricing", "About"],
};

const shared = (mode: ThemeMode, typeface: ThemeTypeface) =>
  `The design system must feel ${mode === "light" ? "light and airy" : "immersive and dark"}, with ${
    typeface === "serif"
      ? "editorial serif typography"
      : typeface === "mono"
        ? "monospaced typography throughout"
        : "clean sans-serif typography"
  }. Keep contrast tight, spacing generous, and let the typography do the work. Return a single self-contained responsive page. Use TailwindCSS, no UI libraries.`;

export const themes: ThemeEntry[] = [
  {
    id: "monochrome",
    name: "Monochrome",
    description:
      "A stark, editorial design system built on pure black and white. No accent colors — just dramatic contrast, oversized type, and confident whitespace.",
    mode: "light",
    typeface: "serif",
    tags: ["editorial", "high-contrast", "minimal"],
    swatch: ["#ffffff", "#0a0a0a", "#e5e5e5"],
    tokens: {
      bg: "#ffffff",
      surface: "#fafafa",
      border: "#0a0a0a",
      text: "#0a0a0a",
      textMuted: "#525252",
      primary: "#0a0a0a",
      primaryText: "#ffffff",
      secondary: "transparent",
      secondaryText: "#0a0a0a",
      accent: "#0a0a0a",
      fontHeading: DISPLAY_SERIF,
      fontBody: SERIF,
      letterSpacingHeading: "-0.04em",
      radius: "0px",
      borderWidth: "1.5px",
      shadow: "none",
      weightHeading: 700,
      headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Redesign this page in the "Monochrome" editorial style. Pure black (#0a0a0a) on pure white (#ffffff). No color accents. Use a display serif for headings (Playfair Display or similar) at very large sizes with tight negative letter-spacing. Thick 1.5px black rules separate sections. Buttons are rectangular (0 radius): primary = solid black with white text, secondary = white with 1.5px black border. Keep body copy in a quiet serif at comfortable size. Generous whitespace. Dramatic contrast is the entire visual language. ${shared("light", "serif")}`,
      claude: `Apply a "Monochrome" editorial design language. Constraints: only #0a0a0a and #ffffff (plus #525252 for muted copy). Typography: Playfair Display / Source Serif Pro. Headings H1 ~72px, weight 700, tracking -0.04em. No rounded corners, no shadows, no gradients. Borders and dividers are 1.5px solid black. Buttons are rectangular; primary is black/white, secondary is white/black with border. Let the page breathe — aim for 80–120px vertical rhythm between sections. ${shared("light", "serif")}`,
      v0: `"Monochrome" theme. Pure black & white. Serif display headings (Playfair), tight negative tracking. 0 radius, 1.5px black borders, no shadows. Primary button: black with white text. Secondary: white with black border. Generous whitespace.`,
      cursor: `Implement a "Monochrome" theme wrapper. Tokens: --bg #fff, --fg #0a0a0a, --muted #525252, --border #0a0a0a, --radius 0, --font-heading "Playfair Display". Apply via :root data-theme="monochrome". Rewrite components to use tokens. No shadows, no gradients, 1.5px black borders, rectangular buttons.`,
    },
  },
  {
    id: "bauhaus",
    name: "Bauhaus",
    description:
      "Primary red, yellow, blue on flat off-white. Geometric shapes, heavy grid, industrial sans-serif. Form follows function.",
    mode: "light",
    typeface: "sans",
    tags: ["geometric", "primary-colors", "modernist"],
    swatch: ["#e63946", "#ffd60a", "#1d4ed8"],
    tokens: {
      bg: "#f5f1e8",
      surface: "#ffffff",
      border: "#111111",
      text: "#111111",
      textMuted: "#444444",
      primary: "#e63946",
      primaryText: "#ffffff",
      secondary: "#ffd60a",
      secondaryText: "#111111",
      accent: "#1d4ed8",
      fontHeading: '"Archivo","Futura","Helvetica Neue",sans-serif',
      fontBody: SANS,
      letterSpacingHeading: "-0.02em",
      radius: "0px",
      borderWidth: "2px",
      shadow: "none",
      weightHeading: 900,
      headingCase: "uppercase",
      decoration: "shapes",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design in the "Bauhaus" style. Palette is strictly primary: signal red (#e63946), pure yellow (#ffd60a), deep blue (#1d4ed8), on a warm off-white canvas (#f5f1e8), with ink black (#111) for type and 2px hairlines. Typography is heavy geometric sans (Archivo / Futura) in UPPERCASE for H1, black weight 900. Compose the page on a visible 12-column grid. Place primitive geometric shapes (circles, triangles, squares) as decorative anchors, each in one primary color — no gradients, no shadows. Buttons are rectangular with 2px borders. ${shared("light", "sans")}`,
      claude: `Create a "Bauhaus" modernist design. Strictly primary colors — red #e63946, yellow #ffd60a, blue #1d4ed8 — on warm off-white #f5f1e8, with 2px black rules. Typography: Archivo Black / Futura, uppercase H1 with heavy weight 900. Everything sits on a 12-col grid; grid lines should be visible in a debug-esque way. Decorate with large primary circles, triangles, and squares. Zero curves other than circles. No shadows. ${shared("light", "sans")}`,
      v0: `Bauhaus theme: primary red/yellow/blue on off-white, black 2px borders, uppercase geometric sans headings, 0 radius, decorative primary-color circles and triangles.`,
      cursor: `Implement "Bauhaus" theme tokens: --bg #f5f1e8, --primary #e63946, --secondary #ffd60a, --accent #1d4ed8, --border #111, --radius 0, --border-w 2px. Headings: uppercase, weight 900, Archivo. Include a set of absolutely-positioned decorative shape divs (circle, triangle, square) in primary colors.`,
    },
  },
  {
    id: "modern-dark",
    name: "Modern Dark",
    description:
      "The default SaaS dark theme done right. Slate backgrounds, indigo accent, subtle gradients, crisp typography.",
    mode: "dark",
    typeface: "sans",
    tags: ["saas", "dark", "modern"],
    swatch: ["#0b0b12", "#6366f1", "#a78bfa"],
    tokens: {
      bg: "#0b0b12",
      surface: "#15151f",
      border: "#26263a",
      text: "#f3f3f7",
      textMuted: "#8b8ba3",
      primary: "#6366f1",
      primaryText: "#ffffff",
      secondary: "transparent",
      secondaryText: "#f3f3f7",
      accent: "#a78bfa",
      fontHeading: SANS,
      fontBody: SANS,
      letterSpacingHeading: "-0.03em",
      radius: "12px",
      borderWidth: "1px",
      shadow: "0 20px 60px -20px rgba(99,102,241,0.25)",
      weightHeading: 700,
      headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design in the "Modern Dark" SaaS style. Backgrounds: near-black slate (#0b0b12), surfaces one shade up (#15151f) with 1px hairline borders (#26263a). Accent: indigo (#6366f1) to violet (#a78bfa) — use it sparingly for primary CTAs and small highlights. Typography: Inter / Geist, tight tracking (-0.03em), 700 weight for H1. Add a very subtle gradient glow behind the hero. Rounded-xl (12px). Tasteful, not flashy — think Linear, Vercel, Raycast. ${shared("dark", "sans")}`,
      claude: `Apply a "Modern Dark" theme. Palette: slate #0b0b12 bg, #15151f surfaces, #f3f3f7 text, #8b8ba3 muted. Accent gradient from indigo #6366f1 to violet #a78bfa used only on primary CTAs. Radius 12px, 1px hairlines. Headings in Geist/Inter, weight 700, tracking-tight. Add a soft 400px-radius indigo glow at the top of the hero. Keep it calm and confident. ${shared("dark", "sans")}`,
      v0: `Modern Dark SaaS theme: slate-950 bg, 1px hairlines, indigo→violet gradient CTAs only, 12px radius, Inter/Geist tracking-tight, subtle top glow.`,
      cursor: `Create the "Modern Dark" theme tokens: --bg #0b0b12, --surface #15151f, --fg #f3f3f7, --muted #8b8ba3, --border #26263a, --primary linear-gradient(90deg,#6366f1,#a78bfa), --radius 12px. Add a blurred radial glow component behind the hero.`,
    },
  },
  {
    id: "newsprint",
    name: "Newsprint",
    description:
      "An old-world broadsheet. Cream paper, ink black, red label accents, Didone headlines, serif body, subtle paper grain.",
    mode: "light",
    typeface: "serif",
    tags: ["editorial", "newspaper", "vintage"],
    swatch: ["#f2ece1", "#0a0a0a", "#b91c1c"],
    tokens: {
      bg: "#f2ece1",
      surface: "#fbf6eb",
      border: "#0a0a0a",
      text: "#0a0a0a",
      textMuted: "#3f3f3f",
      primary: "#0a0a0a",
      primaryText: "#fbf6eb",
      secondary: "transparent",
      secondaryText: "#0a0a0a",
      accent: "#b91c1c",
      fontHeading: '"Playfair Display","Bodoni Moda",Georgia,serif',
      fontBody: '"Source Serif Pro","Lora",Georgia,serif',
      letterSpacingHeading: "-0.02em",
      radius: "0px",
      borderWidth: "1px",
      shadow: "none",
      weightHeading: 900,
      headingCase: "normal",
      grain: true,
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "VOL. III · NO. 42",
      brand: "The Acme Times",
    },
    prompts: {
      chatgpt: `Design a "Newsprint" broadsheet style. Background is cream paper (#f2ece1) with a subtle halftone / paper grain texture. Ink black (#0a0a0a) type throughout. Red (#b91c1c) reserved for small labels, section rules, and dropcap accents. Typography: Playfair Display / Bodoni for display at huge sizes (clamp 64–96px), Source Serif Pro for body. Use 1px hairline rules to separate columns. Dropcap the first paragraph. Treat the logotype like a masthead. Zero shadows, zero rounded corners. ${shared("light", "serif")}`,
      claude: `Create a newspaper "Newsprint" aesthetic. Cream paper #f2ece1, ink #0a0a0a, red accents #b91c1c. Didone display serif headlines (Playfair/Bodoni), weight 900, very large sizes. Body in Source Serif Pro, 18px, generous leading. Layout: multi-column body (2 cols on md+), 1px hairline rules between sections, a visible masthead area. Small red uppercase eyebrows like "Vol. III · No. 42". Add a faint noise SVG filter for paper grain. ${shared("light", "serif")}`,
      v0: `Newsprint theme: cream #f2ece1 paper with grain, black ink, red label accents, Playfair display headlines, multi-col serif body, 1px hairline rules, dropcaps.`,
      cursor: `Implement the "Newsprint" theme. Tokens: --bg #f2ece1, --fg #0a0a0a, --accent #b91c1c, --radius 0, --font-heading "Playfair Display". Add a fixed SVG noise filter overlay at 3% opacity for paper grain. Multi-column body (columns-2 on md+).`,
    },
  },
  {
    id: "saas-clean",
    name: "SaaS Clean",
    description:
      "Fresh, friendly, conversion-optimized. White background, soft blue accent, warm neutral greys, roomy layout.",
    mode: "light",
    typeface: "sans",
    tags: ["saas", "friendly", "marketing"],
    swatch: ["#ffffff", "#2563eb", "#dbeafe"],
    tokens: {
      bg: "#ffffff",
      surface: "#f8fafc",
      border: "#e2e8f0",
      text: "#0f172a",
      textMuted: "#64748b",
      primary: "#2563eb",
      primaryText: "#ffffff",
      secondary: "#f1f5f9",
      secondaryText: "#0f172a",
      accent: "#3b82f6",
      fontHeading: SANS,
      fontBody: SANS,
      letterSpacingHeading: "-0.03em",
      radius: "12px",
      borderWidth: "1px",
      shadow: "0 10px 30px -15px rgba(15,23,42,0.12)",
      weightHeading: 700,
      headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design a clean "SaaS Clean" marketing page. White bg, slate-50 surfaces, 1px slate-200 borders, 12px radius, subtle soft shadows. Accent: blue-600 (#2563eb). Typography: Inter, -0.03em on H1 at ~64px weight 700. Primary CTA is blue with white text; secondary is slate-100 with dark text. Include subtle decorative gradients (blue-100 to transparent) behind the hero. Prioritize conversion: big headline, one-line subcopy, two CTAs, social proof row. ${shared("light", "sans")}`,
      claude: `Apply "SaaS Clean" design tokens. #ffffff bg, #f8fafc surface, #e2e8f0 hairlines, slate-900 text, slate-500 muted, blue-600 primary. Radius 12px, soft 10-20px shadows on cards. Inter with tracking-tight headings. Above-the-fold: small badge, 56–72px headline, 18px subcopy, two CTAs (primary + secondary), trusted-by row with 5 grayscale logos. ${shared("light", "sans")}`,
      v0: `SaaS Clean: white, slate borders, blue-600 accent, Inter tracking-tight, 12px radius, soft shadows, hero + social proof.`,
      cursor: `Tokens for "SaaS Clean": --bg #fff, --surface #f8fafc, --border #e2e8f0, --primary #2563eb, --fg #0f172a, --radius 12px. Apply via data-theme. Primary gradient optional (#3b82f6 to #2563eb).`,
    },
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    description:
      "Ivory, ink, and aged gold. Thin serif type, generous whitespace, delicate rules. For brands that want to feel expensive.",
    mode: "light",
    typeface: "serif",
    tags: ["luxury", "editorial", "gold"],
    swatch: ["#faf6ee", "#1a1a1a", "#b8965c"],
    tokens: {
      bg: "#faf6ee",
      surface: "#ffffff",
      border: "#b8965c",
      text: "#1a1a1a",
      textMuted: "#6b6357",
      primary: "#1a1a1a",
      primaryText: "#faf6ee",
      secondary: "transparent",
      secondaryText: "#1a1a1a",
      accent: "#b8965c",
      fontHeading: '"Cormorant Garamond","Bodoni Moda",Georgia,serif',
      fontBody: '"Cormorant Garamond",Georgia,serif',
      letterSpacingHeading: "-0.015em",
      radius: "2px",
      borderWidth: "0.75px",
      shadow: "none",
      weightHeading: 300,
      headingCase: "normal",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "MAISON ACME — EST. 1893",
      headline: "An enduring standard of craft",
      subcopy:
        "For over a century, Acme has created objects of lasting beauty — considered, restrained, and quietly exceptional.",
      primaryCta: "Explore Collection",
      secondaryCta: "Private Atelier",
    },
    prompts: {
      chatgpt: `Design in the "Luxury Gold" style. Ivory bg (#faf6ee), ink black (#1a1a1a) type, aged-gold (#b8965c) for thin 0.75px rules and small wordmarks. Typography: Cormorant Garamond / light weight 300, with very large serif H1 around 72–96px. Tracking near-zero. Wide line-height. Zero bold. Decorative details: thin gold horizontal rules with a centered ornament (◆ or ·), uppercase tracked small caps for eyebrows. Buttons are text-only with thin 0.75px underline on hover, or ink-filled rectangles. No radius beyond 2px. ${shared("light", "serif")}`,
      claude: `"Luxury Gold" aesthetic. Cormorant Garamond throughout, weight 300. Ivory #faf6ee, ink #1a1a1a, accent gold #b8965c. Use thin 0.75px hairlines in gold. Very large display serif headlines (clamp 64–96px), tracking near zero. Eyebrows are small caps, letter-spaced 0.2em, in gold. Decorative centered ornaments (◆) between sections. Minimum shadows, minimum contrast noise. ${shared("light", "serif")}`,
      v0: `Luxury Gold: ivory + ink + aged gold. Cormorant light 300, huge serif H1, 0.75px gold hairlines with ◆ ornaments, text buttons.`,
      cursor: `"Luxury Gold" tokens: --bg #faf6ee, --fg #1a1a1a, --accent #b8965c, --font-heading "Cormorant Garamond", --weight-heading 300, --border-w 0.75px. Decorative <hr/> with centered ◆.`,
    },
  },
  {
    id: "terminal",
    name: "Terminal",
    description:
      "Hacker aesthetic. Pure black, phosphor green, monospace everything, blinking cursors, ASCII hints of CRT scanlines.",
    mode: "dark",
    typeface: "mono",
    tags: ["hacker", "retro", "dev"],
    swatch: ["#000000", "#00ff88", "#00ccff"],
    tokens: {
      bg: "#000000",
      surface: "#0a0f0a",
      border: "#00ff88",
      text: "#c8ffd6",
      textMuted: "#4ecc7b",
      primary: "#00ff88",
      primaryText: "#000000",
      secondary: "transparent",
      secondaryText: "#00ff88",
      accent: "#00ccff",
      fontHeading: MONO,
      fontBody: MONO,
      letterSpacingHeading: "0em",
      radius: "0px",
      borderWidth: "1px",
      shadow: "0 0 24px rgba(0,255,136,0.35)",
      weightHeading: 500,
      headingCase: "normal",
      decoration: "scanlines",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "> acme_platform.init()",
      headline: "Your team works.\nAcme just makes it faster.",
      primaryCta: "./start_trial",
      secondaryCta: "cat ./demo.md",
    },
    prompts: {
      chatgpt: `Design a "Terminal" CRT hacker interface. Pure black background with a subtle horizontal scanline overlay (2px alternating rows at 4% opacity). All type in a monospace font (JetBrains Mono). Phosphor green (#00ff88) primary, cyan (#00ccff) accent. Headings prefixed with "> " and include a blinking block cursor at the end. Buttons rendered like shell commands: "./start_trial" with bracketed hover states. 1px green borders with a soft green glow (box-shadow). Output lines prefixed with "$". ${shared("dark", "mono")}`,
      claude: `Create a hacker "Terminal" UI. Black bg, phosphor-green #00ff88 primary, #00ccff accent, mono-only typography. Add a scanline overlay (repeating linear-gradient). Headings start with "> " and a blinking ▊ cursor. Body lines feel like stdout ("$ acme --build"). Borders are 1px green with box-shadow glow (0 0 24px green/35). Links are underlined in cyan. ${shared("dark", "mono")}`,
      v0: `Terminal theme: black bg, phosphor green on cyan accent, mono font, scanline overlay, "> " headings with blinking cursor, green glow borders.`,
      cursor: `Implement "Terminal" theme. Tokens: --bg #000, --fg #c8ffd6, --primary #00ff88, --accent #00ccff, --font-body monospace. Add a <div class="scanlines fixed inset-0 pointer-events-none" /> with a repeating-linear-gradient overlay at 4% opacity. Blinking cursor via @keyframes.`,
    },
  },
  {
    id: "swiss",
    name: "Swiss Minimalist",
    description:
      "Classic Swiss/International style. Strict grid, Helvetica, red accent, ruthless alignment, no decoration.",
    mode: "light",
    typeface: "sans",
    tags: ["swiss", "grid", "minimal"],
    swatch: ["#ffffff", "#000000", "#e0301e"],
    tokens: {
      bg: "#ffffff",
      surface: "#ffffff",
      border: "#000000",
      text: "#000000",
      textMuted: "#555555",
      primary: "#000000",
      primaryText: "#ffffff",
      secondary: "transparent",
      secondaryText: "#000000",
      accent: "#e0301e",
      fontHeading: '"Helvetica Neue","Inter",sans-serif',
      fontBody: '"Helvetica Neue","Inter",sans-serif',
      letterSpacingHeading: "-0.03em",
      radius: "0px",
      borderWidth: "1px",
      shadow: "none",
      weightHeading: 700,
      headingCase: "normal",
      decoration: "grid",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design using the "Swiss/International Style". Helvetica Neue throughout. Pure white, pure black, and a single signal red (#e0301e) used for one element per view (rule, dot, or one word). Strict 12-col grid. Left-aligned everything. H1 very large (96–120px), weight 700, -0.03em tracking. Ruthless alignment: all text starts on the same vertical baseline grid. No radius, no shadows, no gradients. Thin 1px black rules between sections. Asymmetric whitespace is the composition. ${shared("light", "sans")}`,
      claude: `Apply "Swiss Minimalist" principles. Helvetica Neue. Black and white with one red (#e0301e) accent per view. Strict 12-col grid (make grid lines visible in a "design mode" toggle, otherwise implied). Giant left-aligned H1 (clamp 80–120px, tracking -0.03em, weight 700). 1px black rules. Zero decoration. Asymmetric whitespace composition. ${shared("light", "sans")}`,
      v0: `Swiss Minimalist: Helvetica, black/white + one red dot/rule, strict 12-col grid, huge left-aligned H1, 1px rules only.`,
      cursor: `"Swiss" theme: --font "Helvetica Neue", --accent #e0301e, --radius 0. Enforce a visible 12-col grid via a debug overlay toggle. H1 should use clamp(4rem, 8vw, 8rem), tracking-[-0.03em], weight 700.`,
    },
  },
  {
    id: "kinetic",
    name: "Kinetic",
    description:
      "Electric orange on near-black. Oversized type with subtle marquee motion, bold uppercase, industrial feel.",
    mode: "dark",
    typeface: "sans",
    tags: ["bold", "energetic", "motion"],
    swatch: ["#0a0a0a", "#ff5b00", "#ffffff"],
    tokens: {
      bg: "#0a0a0a",
      surface: "#141414",
      border: "#ff5b00",
      text: "#ffffff",
      textMuted: "#9a9a9a",
      primary: "#ff5b00",
      primaryText: "#0a0a0a",
      secondary: "transparent",
      secondaryText: "#ffffff",
      accent: "#ff5b00",
      fontHeading: '"Archivo","Space Grotesk","Inter",sans-serif',
      fontBody: SANS,
      letterSpacingHeading: "-0.04em",
      radius: "0px",
      borderWidth: "1px",
      shadow: "none",
      weightHeading: 900,
      headingCase: "uppercase",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "CHAPTER 03 · MOMENTUM",
      headline: "Move fast. Ship faster.",
      primaryCta: "Take the tour",
      secondaryCta: "See changelog",
    },
    prompts: {
      chatgpt: `Design in the "Kinetic" style. Near-black bg (#0a0a0a), white text, electric orange (#ff5b00) accents. Headings are massive uppercase Archivo Black, weight 900, -0.04em tracking, sometimes split across lines with parts in orange. Add a thin marquee-style ticker at the top and bottom scrolling a short tagline in small caps. 1px orange hairlines as section dividers. Buttons are rectangular; primary is orange-filled, secondary is outlined. ${shared("dark", "sans")}`,
      claude: `Apply "Kinetic" theme. Black #0a0a0a, white, orange #ff5b00. Archivo Black uppercase H1 (clamp 72–140px), tracking -0.04em, weight 900. One word or phrase inside H1 switches to orange for emphasis. Add top and bottom marquees with infinite CSS translate animation containing a short repeating phrase in uppercase. 1px orange dividers. ${shared("dark", "sans")}`,
      v0: `Kinetic: black + electric orange, massive uppercase Archivo Black H1 with one-word highlight, top/bottom marquees, 1px orange rules.`,
      cursor: `"Kinetic" tokens: --bg #0a0a0a, --fg #fff, --accent #ff5b00, --radius 0, --font-heading "Archivo Black". Implement top/bottom marquee as a <div class="animate-marquee whitespace-nowrap"> with a keyframe translateX(-50%) at 20s linear infinite.`,
    },
  },
  {
    id: "neo-brutalism",
    name: "Neo-Brutalism",
    description:
      "Hard 4px black borders, flat bright fills, chunky hard-edged shadows, rude sans-serif. Loud on purpose.",
    mode: "light",
    typeface: "sans",
    tags: ["brutalist", "playful", "bold"],
    swatch: ["#ffe14d", "#ff5bbd", "#52d788"],
    tokens: {
      bg: "#fffaea",
      surface: "#ffe14d",
      border: "#000000",
      text: "#000000",
      textMuted: "#333333",
      primary: "#ff5bbd",
      primaryText: "#000000",
      secondary: "#52d788",
      secondaryText: "#000000",
      accent: "#ffe14d",
      fontHeading: '"Space Grotesk","Archivo",sans-serif',
      fontBody: '"Space Grotesk","Inter",sans-serif',
      letterSpacingHeading: "-0.02em",
      radius: "8px",
      borderWidth: "3px",
      shadow: "6px 6px 0 0 #000000",
      weightHeading: 800,
    headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design in the "Neo-Brutalism" style. Butter-cream bg (#fffaea). Surfaces are flat bright fills: yellow (#ffe14d), hot pink (#ff5bbd), or green (#52d788). Everything has 3px solid black borders and a hard-edged 6px 6px 0 black shadow (no blur). 8px radius. No gradients. Space Grotesk headings weight 800, tight tracking. Buttons: primary pink with black shadow; secondary green with black shadow. The aesthetic is unapologetically loud and playful. ${shared("light", "sans")}`,
      claude: `Apply "Neo-Brutalist" design. #fffaea bg, flat fills (#ffe14d / #ff5bbd / #52d788), 3px solid black borders everywhere, 6px 6px 0 black hard shadows. 8px radius. Space Grotesk weight 800 headings. Cards "pop" off the page. Buttons on hover translate 2px down-right and shadow collapses to 2px. ${shared("light", "sans")}`,
      v0: `Neo-Brutalism: cream bg, flat yellow/pink/green fills, 3px black borders, 6px hard shadows, 8px radius, Space Grotesk 800, hover-translate effect.`,
      cursor: `"Neo-Brutalism" tokens: --bg #fffaea, --primary #ff5bbd, --secondary #52d788, --accent #ffe14d, --border #000, --border-w 3px, --shadow 6px 6px 0 #000, --radius 8px. Hover: translate-[2px,2px] and shadow -> 2px 2px 0 #000.`,
    },
  },
  {
    id: "glass",
    name: "Glass",
    description:
      "Translucent frosted cards floating over a vivid gradient sky. Soft glow, 1px white hairlines, modern futurism.",
    mode: "dark",
    typeface: "sans",
    tags: ["glassmorphism", "gradient", "futuristic"],
    swatch: ["#4c1d95", "#db2777", "#0ea5e9"],
    tokens: {
      bg: "radial-gradient(1200px 600px at 70% 10%, #db2777 0%, transparent 45%), radial-gradient(1000px 500px at 10% 80%, #0ea5e9 0%, transparent 45%), linear-gradient(180deg,#1a0b2e,#0a0618)",
      surface: "rgba(255,255,255,0.07)",
      border: "rgba(255,255,255,0.14)",
      text: "#ffffff",
      textMuted: "rgba(255,255,255,0.65)",
      primary:
        "linear-gradient(90deg,#db2777,#a855f7)",
      primaryText: "#ffffff",
      secondary: "rgba(255,255,255,0.06)",
      secondaryText: "#ffffff",
      accent: "#a855f7",
      fontHeading: SANS,
      fontBody: SANS,
      letterSpacingHeading: "-0.03em",
      radius: "20px",
      borderWidth: "1px",
      shadow: "0 30px 80px -20px rgba(0,0,0,0.5)",
      weightHeading: 700,
      headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design a "Glass / Glassmorphism" interface. Background is a vivid gradient sky (purple → magenta → cyan) with 2–3 blurred color orbs. All surfaces are translucent white (bg-white/5 to bg-white/10) with 1px white/10 borders and heavy backdrop-blur. 20px radius. Primary CTA is a pink→purple gradient button; secondary is a glassy pill. Headings are clean Inter tracking-tight. Shadows are soft and large (0 30px 80px -20px black/50). ${shared("dark", "sans")}`,
      claude: `"Glass" theme. Background: radial-gradient orbs (magenta #db2777 + cyan #0ea5e9) over #0a0618. Surfaces: rgba(255,255,255,0.07), border rgba(255,255,255,0.14), backdrop-blur-xl, 20px radius. White text; muted white/65. Primary button: gradient from #db2777 to #a855f7. Large soft drop shadows. ${shared("dark", "sans")}`,
      v0: `Glass theme: vivid gradient bg with blurred orbs, translucent white/5 surfaces with 1px white/10 borders and backdrop-blur-xl, 20px radius, pink→purple gradient CTA.`,
      cursor: `"Glass" theme: body background uses layered radial-gradients. Surfaces get bg-white/5 + border border-white/10 + backdrop-blur-xl. Primary button is a bg-gradient-to-r from-pink-500 to-purple-500. 20px radius globally via --radius.`,
    },
  },
  {
    id: "y2k",
    name: "Y2K Chrome",
    description:
      "Chrome silver gradients, baby blue, sticker pink. Early 2000s iPod-era futurism with glossy rounded buttons.",
    mode: "light",
    typeface: "sans",
    tags: ["y2k", "chrome", "retro"],
    swatch: ["#e4eaff", "#ff7ebf", "#c5cce0"],
    tokens: {
      bg: "linear-gradient(180deg,#eef2ff,#dbeafe)",
      surface:
        "linear-gradient(180deg,#ffffff,#e5ecff)",
      border: "#a0a8c0",
      text: "#0b1330",
      textMuted: "#4b5a86",
      primary:
        "linear-gradient(180deg,#ffb2dc,#ff7ebf)",
      primaryText: "#300a20",
      secondary:
        "linear-gradient(180deg,#ffffff,#c5cce0)",
      secondaryText: "#0b1330",
      accent: "#7c86c3",
      fontHeading: '"Inter","Arial Rounded MT Bold",sans-serif',
      fontBody: SANS,
      letterSpacingHeading: "-0.02em",
      radius: "9999px",
      borderWidth: "1px",
      shadow:
        "inset 0 1px 0 rgba(255,255,255,0.8), 0 8px 20px -8px rgba(60,80,160,0.35)",
      weightHeading: 700,
      headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design in the "Y2K Chrome" style. Background: vertical gradient from indigo-50 to blue-100. Surfaces are glossy pill-shaped cards with vertical white→lavender gradients, 1px #a0a8c0 borders, and an inset top white highlight + soft drop shadow. Buttons are fully rounded (pill) with glossy vertical gradients — primary is baby-pink, secondary is chrome-silver. Accent: lavender-blue. Typography: Inter with slight roundness. Everything feels bubbly and iPod-era. ${shared("light", "sans")}`,
      claude: `"Y2K" / iPod-era chrome. Pale blue gradient bg. Pill-shaped (rounded-full) buttons and cards with glossy vertical gradients and 1px silver borders; every surface has an inset white top highlight (inset 0 1px 0 rgba(255,255,255,0.8)) and a soft drop shadow. Primary: baby pink gradient. Secondary: chrome silver gradient. Playful + shiny + optimistic. ${shared("light", "sans")}`,
      v0: `Y2K Chrome: pale blue gradient bg, rounded-full glossy pill cards & buttons, chrome silver + baby pink gradients, inset top highlights.`,
      cursor: `"Y2K" theme: --radius 9999px, body bg is a linear-gradient. Buttons: background-image: linear-gradient, box-shadow includes an inset top highlight. Preserve a chrome silver gradient utility class.`,
    },
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    description:
      "Synthwave sunset. Magenta and cyan neon on inky purple, perspective grids, Japanese characters as ornament.",
    mode: "dark",
    typeface: "sans",
    tags: ["synthwave", "neon", "retro-futurism"],
    swatch: ["#2b0a3d", "#ff4bd8", "#00e5ff"],
    tokens: {
      bg:
        "radial-gradient(1200px 600px at 50% 100%, #ff4bd8 0%, transparent 40%), linear-gradient(180deg,#16062b,#2b0a3d)",
      surface: "rgba(255,75,216,0.08)",
      border: "rgba(255,75,216,0.35)",
      text: "#ffe9fb",
      textMuted: "#c8a7d9",
      primary: "linear-gradient(90deg,#ff4bd8,#00e5ff)",
      primaryText: "#1a0224",
      secondary: "transparent",
      secondaryText: "#00e5ff",
      accent: "#00e5ff",
      fontHeading: '"Orbitron","Space Grotesk","Inter",sans-serif',
      fontBody: SANS,
      letterSpacingHeading: "0em",
      radius: "6px",
      borderWidth: "1px",
      shadow: "0 0 40px rgba(255,75,216,0.45)",
      weightHeading: 700,
      headingCase: "uppercase",
      decoration: "grid",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "アクメ · SYS.003",
      headline: "Enter the new digital horizon",
    },
    prompts: {
      chatgpt: `Design in "Vaporwave" style. Background: dark purple (#16062b to #2b0a3d) with a hot-pink radial glow at the bottom simulating a sunset, and a perspective neon grid stretching toward the horizon. Neon magenta (#ff4bd8) + neon cyan (#00e5ff). Orbitron uppercase headings with a gradient text fill (pink→cyan) and a soft glow text-shadow. Include a subtle Japanese-character ornament as decoration. Buttons are thin-bordered with a neon-glow drop shadow. ${shared("dark", "sans")}`,
      claude: `"Vaporwave" synthwave. Purple bg with bottom pink sunset glow + perspective grid (CSS transform: rotateX(65deg), linear-gradient stripes). Orbitron uppercase H1 with pink-to-cyan gradient fill and 0 0 30px pink text-shadow glow. Japanese characters (e.g. アクメ) as ornamental labels. Neon borders with box-shadow glow. ${shared("dark", "sans")}`,
      v0: `Vaporwave: purple bg with pink sunset glow + perspective CSS grid, Orbitron uppercase with pink→cyan gradient fill + glow, Japanese-character ornaments.`,
      cursor: `"Vaporwave": perspective grid via a <div> with transform: perspective(400px) rotateX(65deg) and two repeating-linear-gradients in pink. Text gradient via background-clip: text. Add a bottom sunset radial-gradient glow.`,
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description:
      "Neon pink and acid yellow on near-black. Glitch accents, mono body, thin hairlines, ominous pragmatism.",
    mode: "dark",
    typeface: "mono",
    tags: ["cyberpunk", "neon", "glitch"],
    swatch: ["#05050a", "#ff2d87", "#f2ff4a"],
    tokens: {
      bg: "#05050a",
      surface: "#0c0c18",
      border: "#2a2a3a",
      text: "#e8e8f2",
      textMuted: "#7a7a8f",
      primary: "#ff2d87",
      primaryText: "#05050a",
      secondary: "transparent",
      secondaryText: "#f2ff4a",
      accent: "#f2ff4a",
      fontHeading: '"JetBrains Mono","IBM Plex Mono",monospace',
      fontBody: '"JetBrains Mono",monospace',
      letterSpacingHeading: "-0.02em",
      radius: "2px",
      borderWidth: "1px",
      shadow: "0 0 30px rgba(255,45,135,0.35)",
      weightHeading: 600,
      headingCase: "uppercase",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "[ SYS.AUTH ] :: ONLINE",
      headline: "Run the future.\nBefore it runs you.",
      primaryCta: "[ JACK IN ]",
      secondaryCta: "[ READ DOCS ]",
    },
    prompts: {
      chatgpt: `Design in "Cyberpunk" style. Near-black bg (#05050a), mono type only (JetBrains Mono). Neon pink (#ff2d87) for primary/emphasis; acid yellow (#f2ff4a) for secondary. Headings UPPERCASE, weight 600, with occasional glitchy text effect (duplicated text offset by 2px in pink+cyan channels). Buttons are bracketed: "[ JACK IN ]". Borders are thin (1px) with pink glow on hover. Status-bar style labels like "[ SYS.AUTH ] :: ONLINE". ${shared("dark", "mono")}`,
      claude: `Cyberpunk UI. Mono-only. #05050a bg, #e8e8f2 fg, #ff2d87 primary neon pink, #f2ff4a acid yellow. Uppercase H1 with a glitch effect (two absolutely-positioned duplicates, one offset +2px magenta, one -2px cyan, mix-blend-mode screen). Buttons wrapped in brackets "[ JACK IN ]". Dense mono labels like "[ SYS.AUTH ] :: ONLINE" throughout. ${shared("dark", "mono")}`,
      v0: `Cyberpunk: mono, near-black + neon pink + acid yellow, glitch H1 (two offset duplicates, pink+cyan, screen blend), bracketed buttons.`,
      cursor: `"Cyberpunk" theme. Tokens: --bg #05050a, --primary #ff2d87, --accent #f2ff4a, --font-heading monospace. Implement a <Glitch> component that renders its children three times absolutely positioned, two offset with text-shadow in magenta/cyan and mix-blend-mode: screen.`,
    },
  },
  {
    id: "memphis",
    name: "Memphis",
    description:
      "80s Italian design group. Squiggles, polka dots, pastel blocks, chunky shapes colliding with serious geometry.",
    mode: "light",
    typeface: "sans",
    tags: ["80s", "playful", "geometric"],
    swatch: ["#fff8ea", "#ff6b9a", "#4fd1c5"],
    tokens: {
      bg: "#fff8ea",
      surface: "#ffffff",
      border: "#111111",
      text: "#111111",
      textMuted: "#444444",
      primary: "#ff6b9a",
      primaryText: "#111111",
      secondary: "#4fd1c5",
      secondaryText: "#111111",
      accent: "#ffd83d",
      fontHeading: '"Archivo","Space Grotesk",sans-serif',
      fontBody: SANS,
      letterSpacingHeading: "-0.02em",
      radius: "14px",
      borderWidth: "2px",
      shadow: "4px 4px 0 0 #111",
      weightHeading: 800,
      headingCase: "normal",
      decoration: "shapes",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design in the "Memphis" style (1980s Italian design group). Cream bg (#fff8ea). Scatter decorative shapes across the canvas: squiggly lines, polka-dot patterns, zig-zag triangles, pastel blocks, half-circles — in pink (#ff6b9a), teal (#4fd1c5), yellow (#ffd83d), black. Everything has 2px black borders and 4px 4px 0 hard shadows. 14px radius on cards. Playful, asymmetric, collage-like composition. Archivo weight 800 headings. ${shared("light", "sans")}`,
      claude: `"Memphis" 80s pop-design. Cream bg, pink/teal/yellow/black palette, 2px black strokes, 4px hard black shadows, 14px radii. Scatter ~6–8 absolute-positioned decorative SVG shapes across the hero (squiggles, polka dots, triangle patterns, half-circles). Archivo Black headings. Composition is playful asymmetry, not grid. ${shared("light", "sans")}`,
      v0: `Memphis 80s: cream bg, pink/teal/yellow + black, 2px black strokes, 4px hard shadows, scattered squiggle + polka-dot + triangle SVG ornaments.`,
      cursor: `"Memphis" tokens: --bg #fff8ea, --primary #ff6b9a, --secondary #4fd1c5, --accent #ffd83d, --border #111, --border-w 2px, --shadow 4px 4px 0 #111, --radius 14px. Include a <MemphisOrnaments> component rendering 6 absolutely positioned SVG shapes.`,
    },
  },
  {
    id: "scandinavian",
    name: "Scandinavian",
    description:
      "Warm minimal. Beige, sage, soft clay. Generous whitespace, humanist sans, hygge-calm tone.",
    mode: "light",
    typeface: "sans",
    tags: ["warm", "minimal", "natural"],
    swatch: ["#f4efe6", "#7b8c6a", "#c37a5e"],
    tokens: {
      bg: "#f4efe6",
      surface: "#fbf8f2",
      border: "#d9d1c1",
      text: "#2a2720",
      textMuted: "#6a6455",
      primary: "#2a2720",
      primaryText: "#f4efe6",
      secondary: "transparent",
      secondaryText: "#2a2720",
      accent: "#7b8c6a",
      fontHeading: '"Plus Jakarta Sans","Inter",sans-serif',
      fontBody: '"Plus Jakarta Sans","Inter",sans-serif',
      letterSpacingHeading: "-0.025em",
      radius: "14px",
      borderWidth: "1px",
      shadow: "0 10px 30px -18px rgba(80,70,50,0.2)",
      weightHeading: 600,
      headingCase: "normal",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      headline: "Work, with a little more hygge.",
      subcopy:
        "A calm, considered workspace — designed to feel like home, not a factory floor.",
    },
    prompts: {
      chatgpt: `Design in a "Scandinavian" warm-minimal style. Palette: oat #f4efe6, cream #fbf8f2, warm taupe borders #d9d1c1, espresso text #2a2720, sage accent #7b8c6a, clay accent #c37a5e. Typography: Plus Jakarta Sans weight 600 for H1 at modest size (48–64px). Lots of whitespace and long paragraphs at 18px 1.7 leading. Corners 14px. Soft, almost imperceptible shadows. Zero neon. ${shared("light", "sans")}`,
      claude: `"Scandinavian" hygge aesthetic. Oat + cream + sage + warm taupe. Plus Jakarta Sans, weight 600 for heads, 400 for body, 18px 1.7. 14px radii. Very soft shadows. Tone of copy is calm and human. Add a single warm-clay accent on a link or underline. ${shared("light", "sans")}`,
      v0: `Scandinavian: oat + cream + sage, Plus Jakarta Sans, calm tone, 14px radii, very soft shadows, generous leading.`,
      cursor: `"Scandinavian" tokens: --bg #f4efe6, --surface #fbf8f2, --border #d9d1c1, --fg #2a2720, --accent #7b8c6a, --radius 14px, --font-heading "Plus Jakarta Sans".`,
    },
  },
  {
    id: "zen",
    name: "Japanese Zen",
    description:
      "Rice-paper white, sumi ink, vermillion seal. Vertical accents, ample negative space, quiet authority.",
    mode: "light",
    typeface: "serif",
    tags: ["minimal", "japanese", "editorial"],
    swatch: ["#fbf7ef", "#111111", "#c0392b"],
    tokens: {
      bg: "#fbf7ef",
      surface: "#ffffff",
      border: "#111111",
      text: "#111111",
      textMuted: "#555045",
      primary: "#111111",
      primaryText: "#fbf7ef",
      secondary: "transparent",
      secondaryText: "#111111",
      accent: "#c0392b",
      fontHeading:
        '"Noto Serif JP","Source Serif Pro","Playfair Display",serif',
      fontBody: '"Source Serif Pro","Noto Serif JP",serif',
      letterSpacingHeading: "-0.01em",
      radius: "0px",
      borderWidth: "1px",
      shadow: "none",
      weightHeading: 400,
      headingCase: "normal",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      brand: "株式会社 ACME",
      eyebrow: "静 ・ QUIET RELEASE",
      headline: "A quiet system for serious work",
    },
    prompts: {
      chatgpt: `Design in a "Japanese Zen" minimal style. Rice-paper bg (#fbf7ef), sumi-ink text (#111), one vermillion seal-red accent (#c0392b) used very sparingly — like a seal stamp. Typography: Noto Serif JP / Source Serif Pro, light weight 400 headlines at moderate size. Include a vertical Japanese-character label somewhere (e.g. 静 for quiet). Extremely ample whitespace. Thin 1px black rules. No shadows. Composition feels like a ma (間) — meaningful emptiness. ${shared("light", "serif")}`,
      claude: `Japanese "Zen" aesthetic. Rice-paper #fbf7ef, sumi #111, one small vermillion #c0392b seal. Noto Serif JP serif heads, weight 400, moderate size (52–64px). 1px black rules, zero decoration, zero shadow. Include one vertical-writing Japanese character as an ornamental label. Empty space is the primary design element. ${shared("light", "serif")}`,
      v0: `Zen: rice-paper bg, sumi ink, one vermillion seal, Noto Serif JP weight 400, vertical Japanese character ornament, ample emptiness.`,
      cursor: `"Zen" theme: --bg #fbf7ef, --fg #111, --accent #c0392b, --radius 0, --weight-heading 400, --font-heading "Noto Serif JP". Add a <span class="writing-mode-vertical"> component using writing-mode: vertical-rl.`,
    },
  },
  {
    id: "art-deco",
    name: "Art Deco",
    description:
      "Navy, gold, and cream. Symmetric geometric ornament, Didone display type, 1920s poster grandeur.",
    mode: "dark",
    typeface: "serif",
    tags: ["vintage", "geometric", "poster"],
    swatch: ["#0e1b2c", "#d4af37", "#f5ecd7"],
    tokens: {
      bg: "#0e1b2c",
      surface: "#11243c",
      border: "#d4af37",
      text: "#f5ecd7",
      textMuted: "#c9b77a",
      primary: "#d4af37",
      primaryText: "#0e1b2c",
      secondary: "transparent",
      secondaryText: "#d4af37",
      accent: "#d4af37",
      fontHeading: '"Poiret One","Cinzel","Playfair Display",serif',
      fontBody: '"Cormorant Garamond",Georgia,serif',
      letterSpacingHeading: "0.04em",
      radius: "0px",
      borderWidth: "1px",
      shadow: "none",
      weightHeading: 500,
      headingCase: "uppercase",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "THE ACME COMPANY · MCMXXVI",
      headline: "An Exposition of Modern Craft",
      primaryCta: "Reserve Seats",
      secondaryCta: "Programme",
    },
    prompts: {
      chatgpt: `Design in the "Art Deco" (1920s) style. Deep navy (#0e1b2c) bg, gold (#d4af37) accents, cream (#f5ecd7) text. Symmetric layouts. Cinzel/Poiret One uppercase headings with wide tracking (+0.04em). Thin 1px gold rules. Decorative gold sunburst / fan / stepped-pyramid SVG ornaments flanking the hero symmetrically. Deco borders (double-line gold rule with a small diamond between). No shadows, no rounded corners. Grandeur via proportion, not saturation. ${shared("dark", "serif")}`,
      claude: `"Art Deco" theme. Navy #0e1b2c, gold #d4af37, cream #f5ecd7. Typography: Cinzel / Poiret One uppercase H1 with +0.04em tracking. Symmetric compositions. Add gold SVG ornaments: a stepped pyramid or sunburst above the headline, a diamond divider line. Double-rule borders for CTAs (2 thin parallel gold lines). ${shared("dark", "serif")}`,
      v0: `Art Deco: navy + gold + cream, Cinzel uppercase with wide tracking, symmetric SVG ornaments (sunburst, stepped pyramid), double-rule gold borders.`,
      cursor: `"Art Deco" tokens: --bg #0e1b2c, --fg #f5ecd7, --accent #d4af37, --radius 0, --font-heading "Cinzel", tracking 0.04em. Include a <DecoSunburst /> SVG ornament and a double-rule hr component.`,
    },
  },
  {
    id: "cottagecore",
    name: "Cottagecore",
    description:
      "Sage, cream, rust. Hand-drawn sketchy borders, pressed-flower ornaments, warm analog quiet.",
    mode: "light",
    typeface: "serif",
    tags: ["warm", "botanical", "handcraft"],
    swatch: ["#efe6d4", "#6a7a4a", "#b25a3c"],
    tokens: {
      bg: "#efe6d4",
      surface: "#f7f0dd",
      border: "#6a7a4a",
      text: "#3a2e1e",
      textMuted: "#7a6a52",
      primary: "#6a7a4a",
      primaryText: "#f7f0dd",
      secondary: "transparent",
      secondaryText: "#3a2e1e",
      accent: "#b25a3c",
      fontHeading: '"Fraunces","Playfair Display",serif',
      fontBody: '"Fraunces","Lora",serif',
      letterSpacingHeading: "-0.02em",
      radius: "18px",
      borderWidth: "1.5px",
      shadow: "0 14px 30px -18px rgba(90,70,30,0.25)",
      weightHeading: 600,
      headingCase: "normal",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      brand: "Acme & Co.",
      headline: "A slower way of working",
      subcopy:
        "Tools for people who'd rather think about the work than the tools. Pour a cup, settle in.",
    },
    prompts: {
      chatgpt: `Design in "Cottagecore" style. Warm cream bg (#efe6d4) with a soft paper grain. Sage green (#6a7a4a) borders and primary; terracotta (#b25a3c) accent. Typography: Fraunces serif with slight soft optical curves, weight 600 for heads at 56–72px. 18px radii. Thin 1.5px borders. Soft ambient shadows. Scatter small SVG botanical ornaments — a pressed fern, a daisy, a sprig — subtly in the corners. Warm, analog, un-hurried. ${shared("light", "serif")}`,
      claude: `"Cottagecore" theme. Cream + sage + terracotta palette. Fraunces serif, 600 weight heads. 18px radii, 1.5px sage borders, soft shadows. Scatter 3–4 small botanical SVG ornaments (fern frond, daisy, sprig) at corners at low opacity. Body tone is slow and warm. ${shared("light", "serif")}`,
      v0: `Cottagecore: cream + sage + terracotta, Fraunces serif, 18px radii, sage 1.5px borders, scattered botanical SVG ornaments.`,
      cursor: `"Cottagecore" tokens: --bg #efe6d4, --primary #6a7a4a, --accent #b25a3c, --fg #3a2e1e, --radius 18px, --font-heading Fraunces. Include a <BotanicalOrnaments /> component with 3–4 absolutely-positioned low-opacity botanical SVGs.`,
    },
  },
  {
    id: "concrete",
    name: "Concrete",
    description:
      "Raw architectural grey. Mono labels, large type, industrial precision, zero warmth.",
    mode: "light",
    typeface: "mono",
    tags: ["industrial", "architecture", "cold"],
    swatch: ["#dcdcdc", "#1a1a1a", "#8a8a8a"],
    tokens: {
      bg: "#dcdcdc",
      surface: "#e8e8e8",
      border: "#1a1a1a",
      text: "#1a1a1a",
      textMuted: "#5a5a5a",
      primary: "#1a1a1a",
      primaryText: "#dcdcdc",
      secondary: "transparent",
      secondaryText: "#1a1a1a",
      accent: "#1a1a1a",
      fontHeading: '"JetBrains Mono","IBM Plex Mono",monospace',
      fontBody: '"JetBrains Mono",monospace',
      letterSpacingHeading: "-0.02em",
      radius: "0px",
      borderWidth: "1px",
      shadow: "none",
      weightHeading: 500,
      headingCase: "uppercase",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      eyebrow: "001 / PLATFORM / RELEASE 3.0",
      headline: "Infrastructure for the way teams actually work.",
    },
    prompts: {
      chatgpt: `Design in a "Concrete" / architectural style. Raw concrete grey bg (#dcdcdc). Everything in JetBrains Mono. Headings UPPERCASE, weight 500, left-aligned, modest tracking. Numbered section labels like "001 / PLATFORM / RELEASE 3.0". 1px ink-black hairlines everywhere. No radius. No shadow. No color except grey and black. Precise, cold, honest. ${shared("light", "mono")}`,
      claude: `"Concrete" theme. Raw grey #dcdcdc bg, mono only, black ink, no accent color. 1px black rules. Uppercase headings weight 500 with mild negative tracking. Pepper the design with technical-style metadata labels: "001 / PLATFORM / RELEASE 3.0", "FIG. 1", "§ 02". ${shared("light", "mono")}`,
      v0: `Concrete: raw grey bg, mono only, 1px black rules, uppercase mono headings, numbered metadata labels, zero ornament.`,
      cursor: `"Concrete" tokens: --bg #dcdcdc, --fg #1a1a1a, --radius 0, --font-body monospace, --border-w 1px. Headings uppercase, numbered labels prefixed in a <Label> component.`,
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description:
      "Warm peach → coral → violet gradients. Rounded soft cards, friendly geometric sans. Optimistic.",
    mode: "light",
    typeface: "sans",
    tags: ["gradient", "warm", "friendly"],
    swatch: ["#fff1e0", "#ff6e7f", "#bfe9ff"],
    tokens: {
      bg:
        "radial-gradient(1000px 500px at 80% 0%, #ffd0a2 0%, transparent 50%), radial-gradient(900px 500px at 0% 100%, #ffafc5 0%, transparent 50%), linear-gradient(180deg,#fff6ec,#ffe6ee)",
      surface: "rgba(255,255,255,0.75)",
      border: "rgba(255,110,127,0.22)",
      text: "#2a1420",
      textMuted: "#6a4a55",
      primary:
        "linear-gradient(90deg,#ff8a5b,#ff6e7f)",
      primaryText: "#ffffff",
      secondary: "rgba(255,255,255,0.6)",
      secondaryText: "#2a1420",
      accent: "#ff6e7f",
      fontHeading: '"Plus Jakarta Sans","Inter",sans-serif',
      fontBody: '"Plus Jakarta Sans","Inter",sans-serif',
      letterSpacingHeading: "-0.03em",
      radius: "22px",
      borderWidth: "1px",
      shadow: "0 24px 50px -20px rgba(255,110,127,0.3)",
      weightHeading: 700,
      headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design in the "Sunset" warm-gradient style. Background is a painterly multi-radial gradient: peach at top-right, pink at bottom-left, cream overall. Surfaces are translucent white with 1px rose-tinted borders (rgba(255,110,127,0.22)), 22px radii, a soft warm pink-shadow glow. Primary CTA is a peach→coral gradient button. Typography: Plus Jakarta Sans weight 700 with tight tracking. Friendly, optimistic, warm. ${shared("light", "sans")}`,
      claude: `"Sunset" theme. Painterly warm gradient bg (peach + pink radials over cream). Translucent white surfaces with a rose 1px border, 22px radii, warm pink drop shadow. Plus Jakarta Sans. Primary button: peach→coral linear gradient. Tone is optimistic and warm. ${shared("light", "sans")}`,
      v0: `Sunset: peach + pink radial gradient bg, translucent white cards with rose borders, 22px radii, peach→coral gradient CTA.`,
      cursor: `"Sunset" tokens: body background uses 2 radial-gradients + 1 linear-gradient. --surface rgba(255,255,255,0.75), --border rgba(255,110,127,0.22), --radius 22px. Primary button gradient.`,
    },
  },
  {
    id: "forest",
    name: "Forest",
    description:
      "Deep pine and moss. Textured dark green, amber glints, calm outdoor magazine energy.",
    mode: "dark",
    typeface: "serif",
    tags: ["nature", "dark", "warm-dark"],
    swatch: ["#0f1d15", "#cbe2b0", "#e2a345"],
    tokens: {
      bg: "#0f1d15",
      surface: "#14291e",
      border: "#2b4331",
      text: "#e9efe1",
      textMuted: "#9bb19a",
      primary: "#e2a345",
      primaryText: "#0f1d15",
      secondary: "transparent",
      secondaryText: "#cbe2b0",
      accent: "#cbe2b0",
      fontHeading: '"Fraunces","Source Serif Pro",serif',
      fontBody: '"Source Serif Pro","Fraunces",serif',
      letterSpacingHeading: "-0.02em",
      radius: "10px",
      borderWidth: "1px",
      shadow: "0 20px 50px -20px rgba(0,0,0,0.45)",
      weightHeading: 600,
      headingCase: "normal",
    },
    sample: {
      ...DEFAULT_SAMPLE,
      headline: "Work, at the pace of the outdoors",
    },
    prompts: {
      chatgpt: `Design in a "Forest" outdoor-magazine style. Deep pine bg (#0f1d15), moss surface (#14291e), sage text (#e9efe1), amber accent (#e2a345) reserved for primary CTAs and small highlights. Fraunces serif headings, weight 600, 56–72px, tight tracking. 10px radii. Add a subtle noise/grain texture on the bg to feel photographic. Warm, calm, confident. ${shared("dark", "serif")}`,
      claude: `"Forest" theme. Pine + moss + sage palette, amber accent. Fraunces serif. 10px radii, 1px moss borders. Subtle noise-texture overlay on the body bg. Warm dark aesthetic — outdoors magazine. ${shared("dark", "serif")}`,
      v0: `Forest: pine bg + sage text + amber CTA, Fraunces serif 600, 10px radii, subtle noise texture.`,
      cursor: `"Forest" tokens: --bg #0f1d15, --surface #14291e, --fg #e9efe1, --accent #e2a345, --radius 10px, --font-heading Fraunces. Add a fixed noise SVG overlay at 4% opacity.`,
    },
  },
  {
    id: "pastel-ui",
    name: "Pastel UI",
    description:
      "Soft mint, peach, lilac backgrounds with high-contrast black type. Rounded, friendly, mobile-first.",
    mode: "light",
    typeface: "sans",
    tags: ["pastel", "rounded", "playful"],
    swatch: ["#e8f7ef", "#fde3d4", "#ecdcff"],
    tokens: {
      bg:
        "linear-gradient(180deg,#fff6ef,#eef7ff)",
      surface: "#ffffff",
      border: "#111111",
      text: "#111111",
      textMuted: "#555555",
      primary: "#a78bfa",
      primaryText: "#111111",
      secondary: "#fde3d4",
      secondaryText: "#111111",
      accent: "#52d788",
      fontHeading: '"Space Grotesk","Inter",sans-serif',
      fontBody: '"Space Grotesk","Inter",sans-serif',
      letterSpacingHeading: "-0.02em",
      radius: "24px",
      borderWidth: "2px",
      shadow: "0 14px 36px -16px rgba(20,20,60,0.12)",
      weightHeading: 700,
      headingCase: "normal",
    },
    sample: DEFAULT_SAMPLE,
    prompts: {
      chatgpt: `Design in a "Pastel UI" style. Body bg is a gentle gradient from cream to ice-blue. Surfaces are white with 2px pure-black borders and a soft subtle shadow. 24px radii. Primary actions use pastel lilac (#a78bfa) fills with black text; secondaries use peach (#fde3d4). Green (#52d788) accent. Space Grotesk headings weight 700. Friendly, rounded, accessible. ${shared("light", "sans")}`,
      claude: `"Pastel UI". Cream-to-ice-blue gradient bg. White surfaces with 2px black borders + soft shadows + 24px radii. Palette: lilac primary, peach secondary, mint accent. Space Grotesk 700 heads. Warm black text for contrast. ${shared("light", "sans")}`,
      v0: `Pastel UI: cream/ice-blue gradient bg, white 2px-black-bordered cards, 24px radii, lilac + peach + mint, Space Grotesk 700.`,
      cursor: `"Pastel UI" tokens: --radius 24px, --border #111, --border-w 2px, --primary #a78bfa, --secondary #fde3d4, --accent #52d788. Body uses a linear-gradient bg.`,
    },
  },
];

export function getTheme(id: string) {
  return themes.find((t) => t.id === id);
}
